apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 3
  storage:
    storageClass: csi-cephfs-sc
    size: 1Gi
  managed:
    roles:
    - name: app
      ensure: absent
    services:
      disabledDefaultServices: ["ro"]
