apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 3
  storage:
    storageClass: csi-cephfs-sc
    size: 1Gi
  managed:
    roles:
    - name: app
      ensure: absent
    - name: compeng
      ensure: present
      login: true
      passwordSecret:
        name: cnpg-compeng
    - name: forgejo
      ensure: present
      login: true
      passwordSecret:
        name: cnpg-forgejo
    services:
      disabledDefaultServices: ["ro"]
