apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
spec:
  name: forgejo
  owner: forgejo
  cluster:
    name: {{ .Release.Name }}
  ensure: present
