kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: forgejo-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
