apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: forgejo
  ports:
    - name: ssh
      protocol: TCP
      port: 22
    - name: http
      protocol: TCP
      port: 3000
