apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
spec:
  secretName: pihole-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
  - {{ .Values.host }}
