apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pihole-dns-tcp
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - dns-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: pihole
      port: 53
