apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-websecure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`)
    services:
    - name: pihole
      port: 80
  tls:
    secretName: pihole-tls
