apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - dns
  routes:
    - services:
        - name: pihole
          port: 53
