apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
    - name: dns
      protocol: UDP
      port: 53
    - name: http
      protocol: TCP
      port: 80
