apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discordbot
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}-discordbot
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-discordbot
    spec:
      containers:
      - image: ghcr.io/compeng-gg/compeng-gg-backend:latest
        command: ["python", "-u", "manage.py", "rundiscordbot"]
        name: {{ .Release.Name }}-discordbot
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-backend
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-discordbot
  