apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}-backend
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-backend
    spec:
      containers:
      - image: ghcr.io/compeng-gg/compeng-gg-backend:latest
        name: {{ .Release.Name }}-backend
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-backend
  