apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}-frontend
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-frontend
    spec:
      containers:
      - image: code.ece.gg/compeng-gg/compeng-frontend:latest
        name: {{ .Release.Name }}-frontend
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-frontend
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
      imagePullSecrets:
      - name: docker
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-frontend
  