apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}-backend
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-backend
    spec:
      serviceAccountName: webhook
      containers:
      - image: code.ece.gg/compeng-gg/compeng-backend:latest
        imagePullPolicy: Always
        name: {{ .Release.Name }}-backend
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-backend
        ports:
        - name: http
          protocol: TCP
          containerPort: 8000
      imagePullSecrets:
      - name: docker
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-backend
  