apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-websecure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: (Host(`{{ .Values.host }}`) || Host(`www.{{ .Values.host }}`)) && PathPrefix(`/api`)
    middlewares:
    - name: redirect-canonical
    services:
    - name: {{ .Release.Name }}-backend
      port: 8000
  - kind: Rule
    match: Host(`{{ .Values.host }}`) || Host(`www.{{ .Values.host }}`)
    middlewares:
    - name: redirect-canonical
    services:
    - name: {{ .Release.Name }}-frontend
      port: 3000
  tls:
    secretName: {{ .Release.Name }}-tls
