apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/attach", "pods/eviction", "pods/exec", "pods/log", "pods/status"]
  verbs: ["*"]
