apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: compeng
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io

