apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
