apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - image: ghcr.io/ceresforge/ceresforge:latest
        name: {{ .Release.Name }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  