apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) || Host(`www.{{ .Values.domain }}`)
    middlewares:
    - name: redirect-canonical
    services:
    - name: noop@internal
      kind: TraefikService
