apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-websecure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) || Host(`www.{{ .Values.domain }}`)
    middlewares:
    - name: redirect-canonical
    services:
    - name: {{ .Release.Name }}
      port: 8080
  tls:
    secretName: {{ .Release.Name }}-tls
