apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - image: vaultwarden/server:1.34.1
        name: {{ .Release.Name }}
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        env:
        - name: DOMAIN
          value: "https://{{ .Values.host }}"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: admin-token
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  