apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rgw
  namespace: {{ .Release.Namespace }}
spec:
  secretName: rgw-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
  - {{ .Values.host }}
  - '*.{{ .Values.host }}'
