apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rgw-websecure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`^.+\.{{ .Values.domain | replace "." "\\." }}$`) || Host(`{{ .Values.domain }}`)
    services:
    - name: rgw
      port: 7480
  tls:
    secretName: rgw-tls
