apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-websecure
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.host }}`)
    services:
    - name: proxmox
      port: 8006
      scheme: https
      serversTransport: insecure@kubernetescrd
  tls:
    secretName: proxmox-tls
