apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-web
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.host }}`)
    middlewares:
    - name: redirect-https
    services:
    - name: noop@internal
      kind: TraefikService
